name: adaptive_learning_env
channels:
  - defaults
dependencies:
  - python==3.8
  - pandas==2.1.3
  - plotly==5.18.0
  - dash==2.14.2
  - dash-mantine-components==0.10.2
  - dash-iconify==0.1.2
  - SQLAlchemy==2.0.25
  - dash-html-components==2.0.0
  - dash-bootstrap-components==1.5.0
  - dash-core-components==2.0.0
  - scikit-learn==1.3.2
  - caserecommender==1.1.1
